title: Rust-lang Belgium user group
description: Rust-lang Belgium user group
baseurl: ""
url: "http://rust-lang.be/"
#twitter_username: jekyllrb
github_username:  Grummfy
show_downloads: false
google_analytics: UA-91780964-2

theme: jekyll-theme-cayman
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
